[package]
name = "gptut"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.140"
reqwest = { version = "0.12.15", features = ["json"] }
tokio = { version = "1.44.2", features = ["full"] }
clap = { version = "4.5.37", features = ["derive"] }
dialoguer = "0.11.0"
mockito = "*"
